Repository matrixbytes/Obfussor, pull requests merged in 2025-10, with the labels that each got.

#8 #3 Angular version changed to 17.3.12
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.config.ts
  tsconfig.app.json
  tsconfig.json
Labels: enhancement, good first issue, hacktoberfest-2025

#13 fix(tsconfig): enable composite mode for tsconfig.app.json
  tsconfig.app.json
Labels: bug, hacktoberfest, Frontend

#17 #5 Created Proper Application Layout
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/layout/layout.component.css
  src/app/components/layout/layout.component.html
  src/app/components/layout/layout.component.ts
  src/app/components/sidebar/sidebar.component.css
  src/app/components/sidebar/sidebar.component.html
  src/app/components/sidebar/sidebar.component.ts
  src/app/views/build/build.component.ts
  src/app/views/dashboard/dashboard.component.css
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
  src/app/views/projects/projects.component.ts
  src/app/views/reports/reports.component.ts
  src/app/views/settings/settings.component.ts
  src/styles.css
Labels: enhancement, hacktoberfest, Frontend, hacktoberfest-accepted

#21 CI: fix Windows normalize step; robust smoke harness
  .github/workflows/tests.yml
  .gitignore
  .vscode/settings.json
  tests/normalize_obfucc.ps1
  tests/run_regressions.sh
  tests/run_smoke.sh
Labels: enhancement, hacktoberfest-accepted, CI | CD

#56 feat: add ESLint and Prettier configuration for code quality
  .eslintrc.json
  .prettierrc
  CONTRIBUTING.md
  eslint.config.js
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.config.ts
  src/app/app.routes.ts
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/layout/layout.component.css
  src/app/components/layout/layout.component.html
  src/app/components/layout/layout.component.ts
  src/app/components/sidebar/sidebar.component.css
  src/app/components/sidebar/sidebar.component.html
  src/app/components/sidebar/sidebar.component.ts
  src/app/views/build/build.component.ts
  src/app/views/dashboard/dashboard.component.css
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
  src/app/views/projects/projects.component.ts
  src/app/views/reports/reports.component.ts
  src/app/views/settings/settings.component.ts
  src/main.ts
  src/styles.css
  tsconfig.app.json
Labels: documentation, enhancement, hacktoberfest-accepted, dependencies

#63 CI: [ upd branch to master ]
  .github/workflows/mdbook.yml
Labels: CI | CD
